import { microserviceClient } from "../../services/microserviceClient.js";

export const aiResolvers = {
  Query: {
    health: () => "Gateway is running!",

    healthCheck: async () => {
      const servicesHealth = await microserviceClient.healthCheck();

      return {
        timestamp: servicesHealth.timestamp || new Date().toISOString(),
        services: {
          erp: servicesHealth.services?.erp || {
            status: "unknown",
            message: "Service not responding",
          },
          ml: servicesHealth.services?.ml || {
            status: "unknown",
            message: "Service not responding",
          },
          bi: servicesHealth.services?.bi || null,
        },
      };
    },

    recommendations: async (_, { userId }) => {
      try {
        // Simulamos recomendaciones basadas en IA
        const mockRecommendations = [
          {
            id: "1",
            userId: userId,
            productId: "101",
            score: 0.95,
            reason: "Based on purchase history and preferences",
          },
          {
            id: "2",
            userId: userId,
            productId: "102",
            score: 0.87,
            reason: "Similar users also liked this product",
          },
          {
            id: "3",
            userId: userId,
            productId: "103",
            score: 0.82,
            reason: "Trending product in your category",
          },
        ];
        return mockRecommendations;
      } catch (error) {
        console.error("Error generating recommendations:", error.message);
        return [];
      }
    },
  },

  Mutation: {
    generateRecommendation: async (_, { userId, productId }) => {
      try {
        // Simulamos la generación de una recomendación personalizada
        const recommendation = {
          id: Date.now().toString(),
          userId: userId,
          productId: productId,
          score: Math.random() * 0.3 + 0.7, // Score entre 0.7 y 1.0
          reason: "Generated by AI algorithm based on user behavior and product analytics",
        };

        console.log(`🤖 Generated AI recommendation for user ${userId} and product ${productId}`);
        return recommendation;
      } catch (error) {
        console.error("Error generating recommendation:", error.message);
        throw new Error("Failed to generate recommendation");
      }
    },
  },
};
